### ISSUE TITLE
Calendar Component

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_react#1]
EPIC <Epic>

Allow **User** to **select days** so they can see which days **have tasks** in them

**Acceptance Criteria**
- [ ] Comments in the code
- [ ] Days with tasks display a minuature representation of tasks
- [ ] Navigation between Months
- [ ] Selecting a Day returns a date

**Tasks**
- [ ] Create React Component named Calendar
