### ISSUE TITLE
Task Component

### ISSUE THREAD

**Issue by dimitri-edel** [dimitri-edel/organizer_react#2]
EPIC <Epic>

Allow ** User ** to**view individual tasks**

**Acceptance Criteria**
- [ ] Comments in the code
- [ ] Communication with API

**Tasks**
- [ ] Update function
- [ ] Delete function
- [ ] Reflect fields of the objects delivered by the API
